FROM docker.io/library/ros:kilted-ros-core AS build

# Install pixi
RUN apt update && apt install -y git && curl -fsSL https://pixi.sh/install.sh | bash
ENV PATH="/root/.pixi/bin:$PATH"

# Build the workspace
COPY aic_example_policies /ws_aic/src/aic/aic_example_policies
COPY aic_model /ws_aic/src/aic/aic_model
COPY aic_interfaces /ws_aic/src/aic/aic_interfaces
COPY aic_utils /ws_aic/src/aic/aic_utils
COPY pixi.toml pixi.lock /ws_aic/src/aic/

# Add other local dependencies

SHELL ["/bin/bash", "-c"]
RUN --mount=type=cache,target=/root/.cache/rattler/cache --mount=type=cache,target=/ws_aic/src/aic/.pixi/build \
    cd /ws_aic/src/aic && pixi install --frozen

COPY pixi_env_setup.sh /ws_aic/src/aic/

WORKDIR /ws_aic/src/aic
COPY --chmod=755 <<"EOF" /start_model.sh
#!/bin/bash
set -e

export RMW_IMPLEMENTATION=rmw_zenoh_cpp

if [[ -z "$AIC_MODEL_ROUTER_ADDR" ]]; then
  echo "AIC_MODEL_ROUTER_ADDR must be provided"
  exit 1
fi

should_disable_acl() {
  [[ "$AIC_DISABLE_ACL" == "true" || "$AIC_DISABLE_ACL" == "1" ]]
}

# prepare the credentials file
if ! should_disable_acl; then
  if [[ ! (-n "$AIC_MODEL_PASSWD" && -n "$AIC_MODEL_ROUTER_PASSWD") ]]; then
    echo "AIC_MODEL_PASSWD, AIC_MODEL_ROUTER_PASSWD must be provided"
    exit 1
  fi
  echo "model:$AIC_MODEL_PASSWD" >> /credentials.txt
  echo "model-router:$AIC_MODEL_ROUTER_PASSWD" >> /credentials.txt
fi

# start the model
ZENOH_CONFIG_OVERRIDE='connect/endpoints=["tcp/'"$AIC_MODEL_ROUTER_ADDR"'"]'
if ! should_disable_acl; then
  ZENOH_CONFIG_OVERRIDE+=';transport/auth/usrpwd/user="model"'
  ZENOH_CONFIG_OVERRIDE+=';transport/auth/usrpwd/password="'"$AIC_MODEL_PASSWD"'"'
  ZENOH_CONFIG_OVERRIDE+=';transport/auth/usrpwd/dictionary_file="/credentials.txt"'
fi
export ZENOH_CONFIG_OVERRIDE
echo "ZENOH_CONFIG_OVERRIDE=$ZENOH_CONFIG_OVERRIDE"
exec pixi run --as-is ros2 run aic_model aic_model "$@"
EOF

COPY --chmod=755 <<"EOF" /entrypoint.sh
#!/bin/bash
set -e

AIC_DISABLE_ACL=${AIC_DISABLE_ACL:-1} exec /start_model.sh "$@"
EOF

# Contary to the name, `/entrypoint.sh` is not actually the entrypoint.
# The name is kept to maintain compatibility as the old entrypoint script does not have ACL.
ENTRYPOINT ["/start_model.sh"]
